openapi: 3.0.0
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: AccessToken
  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          example: Password123!
        role:
          type: string
          enum: [user, admin]
          default: user
        isVerified:
          type: boolean
          default: false
    RegisterResponse:
      type: object
      properties:
        message:
          type: string
          example: registered
        user:
          type: object
          properties:
            email:
              type: string
              example: user@example.com
            otp:
              type: string
              example: "123456"
            otpTime:
              type: integer
              example: 1698076800000
    VerifyRequest:
      type: object
      required:
        - email
        - otp
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        otp:
          type: string
          example: "123456"
    VerifyResponse:
      type: object
      properties:
        message:
          type: string
          example: verify
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          example: Password123!
    LoginResponse:
      type: object
      properties:
        message:
          type: string
          example: success
        access:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
    LogoutResponse:
      type: object
      properties:
        message:
          type: string
          example: log out
    ResetPasswordRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          example: NewPassword123!
    ResetPasswordResponse:
      type: object
      properties:
        message:
          type: string
          example: reset password success
    UserResponse:
      type: object
      properties:
        _id:
          type: string
          example: 507f1f77bcf86cd799439011
        email:
          type: string
          example: user@example.com
        role:
          type: string
          example: user
        createdAt:
          type: string
          format: date-time
          example: 2023-10-23T12:00:00Z
    AdminUserResponse:
      type: object
      properties:
        _id:
          type: string
          example: 507f1f77bcf86cd799439011
        email:
          type: string
          example: user@example.com
        role:
          type: string
          example: admin
        createdAt:
          type: string
          format: date-time
          example: 2023-10-23T12:00:00Z
        category:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        cars:
          type: array
          items:
            $ref: '#/components/schemas/Car'
    Car:
      type: object
      properties:
        _id:
          type: string
          example: 507f1f77bcf86cd799439012
        brand:
          type: string
          example: Toyota
        model:
          type: string
          example: Camry
        year:
          type: integer
          example: 2020
        motor:
          type: string
          example: 2.5L
        color:
          type: string
          example: Blue
        distance:
          type: integer
          example: 50000
        gearbox:
          type: string
          example: Automatic
        price:
          type: number
          example: 25000
        frontImage:
          type: string
          example: front.jpg
        backImage:
          type: string
          example: back.jpg
        modelImage:
          type: string
          example: model.jpg
        description:
          type: string
          example: A well-maintained sedan with low mileage.
        owner_id:
          type: string
          example: 507f1f77bcf86cd799439011
        category_id:
          type: string
          example: 507f1f77bcf86cd799439013
    CarCreateRequest:
      type: object
      required:
        - brand
        - model
        - year
        - motor
        - color
        - distance
        - gearbox
        - price
        - description
        - owner_id
        - category_id
        - frontImage
        - backImage
        - modelImage
      properties:
        brand:
          type: string
          example: Toyota
        model:
          type: string
          example: Camry
        year:
          type: integer
          example: 2020
        motor:
          type: string
          example: 2.5L
        color:
          type: string
          example: Blue
        distance:
          type: integer
          example: 50000
        gearbox:
          type: string
          example: Automatic
        price:
          type: number
          example: 25000
        description:
          type: string
          example: A well-maintained sedan with low mileage.
        owner_id:
          type: string
          example: 507f1f77bcf86cd799439011
        category_id:
          type: string
          example: 507f1f77bcf86cd799439013
        frontImage:
          type: string
          format: binary
        backImage:
          type: string
          format: binary
        modelImage:
          type: string
          format: binary
    CarCreateResponse:
      type: object
      properties:
        message:
          type: string
          example: Careated
    CarGetResponse:
      type: object
      properties:
        message:
          type: string
          example: Car retrieved successfully
    CarUpdateRequest:
      type: object
      required:
        - brand
        - model
        - year
        - motor
        - color
        - distance
        - gearbox
        - price
        - description
        - owner_id
      properties:
        brand:
          type: string
          example: Toyota
        model:
          type: string
          example: Camry
        year:
          type: integer
          example: 2020
        motor:
          type: string
          example: 2.5L
        color:
          type: string
          example: Blue
        distance:
          type: integer
          example: 50000
        gearbox:
          type: string
          example: Automatic
        price:
          type: number
          example: 25000
        description:
          type: string
          example: A well-maintained sedan with low mileage.
        owner_id:
          type: string
          example: 507f1f77bcf86cd799439011
        frontImage:
          type: string
          format: binary
        backImage:
          type: string
          format: binary
        modelImage:
          type: string
          format: binary
    CarUpdateResponse:
      type: object
      properties:
        message:
          type: string
          example: Car updated
    CarDeleteResponse:
      type: object
      properties:
        message:
          type: string
          example: Car deleted
    Category:
      type: object
      properties:
        _id:
          type: string
          example: 507f1f77bcf86cd799439013
        name:
          type: string
          example: Sedan
        img:
          type: string
          example: category.jpg
        owner_id:
          type: string
          example: 507f1f77bcf86cd799439011
        cars:
          type: array
          items:
            $ref: '#/components/schemas/Car'
    CategoryCreateRequest:
      type: object
      required:
        - name
        - owner_id
        - img
      properties:
        name:
          type: string
          example: Sedan
        owner_id:
          type: string
          example: 507f1f77bcf86cd799439011
        img:
          type: string
          format: binary
    CategoryCreateResponse:
      type: object
      properties:
        message:
          type: string
          example: Category created
    CategoryGetResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Category'
    CategoryUpdateRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: Sedan
        img:
          type: string
          format: binary
    CategoryUpdateResponse:
      type: object
      properties:
        message:
          type: string
          example: Category updated
    CategoryDeleteResponse:
      type: object
      properties:
        message:
          type: string
          example: Category deleted
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: Error message